@startuml
!theme aws-orange
left to right direction

actor Scientist as "Environmental Scientist"

rectangle Database

rectangle "System" {

    usecase UC1 as "View Sensors"
    usecase UC2 as "Generate Trends Report"
    usecase UC3 as "Cannot calculate too few data values"
    usecase UC4 as "Cannot find sensors in database"

    Scientist --> UC1
    Scientist --> UC2

    UC2 <. UC3 : extends
    UC1 <. UC4 : extends

    UC1 --> Database
    UC2 --> Database

}
@enduml